# Numpy

Numpy is python package/library which stands Numerical Python.

**Use of Numpy in Data Analytics ?** --> Numpy is used to handle large dataset and To perform mathematical and statistical operation on arrays.

Python List vs Numpy arry
1) The operation which we perform on numpy arrays are faster than python list , bacuase numpy arrays hold similary data type element and also numpy is implemented on C langauge.

2) In terms of memory utilazation also numpy array are more memory efficient than python list.

Generally:
1) 1D --> Vector
2) 2D --> Matrix
3) 3D --> Tensors

In [4]:
import numpy as np

### Array Creation

#### 1D array

In [9]:
# zero dimension array

arr = np.array(50)
print(type(arr))
print("dimension :",arr.ndim)
arr

<class 'numpy.ndarray'>
dimension : 0


array(50)

In [72]:
# scaler and vector

num = 40 # integer , float
print(num) 



40


In [18]:
# vector --> array of scaler values , generally vectors are 1D array
arr = np.array([2,3,4,5,6])
print(arr)
print(type(arr))
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)

[2 3 4 5 6]
<class 'numpy.ndarray'>
dimension : 1
shape : (5,)
size : 5


In [20]:
# make and 1D array using users input
lst = []
size = int(input("enter size of array :"))
for i in range(size):
    n = int(input("enter element :"))
    lst.append(n)
arr = np.array(lst)
arr

enter size of array : 5
enter element : 1
enter element : 2
enter element : 3
enter element : 4
enter element : 5


array([1, 2, 3, 4, 5])

#### 2D array

2D array is an array of 1D array

In [22]:
arr = np.array([ [2,3,4] ])
print(arr)
print(type(arr))
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)

[[2 3 4]]
<class 'numpy.ndarray'>
dimension : 2
shape : (1, 3)
size : 3


In [27]:
arr = np.array([[2,3,4],
                  [5,6,7],
                   [7,8,9]])
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)

[[2 3 4]
 [5 6 7]
 [7 8 9]]
dimension : 2
shape : (3, 3)
size : 9


#### 3D
It is an array of 2D arrays

In [35]:
arr = np.array([ [[2,3],[4,5]] ])
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)

[[[2 3]
  [4 5]]]
dimension : 3
shape : (1, 2, 2)
size : 4


In [36]:
arr = np.array([ [[2,3],[4,5]], [[6,7],[8,9]]])
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)

[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]
dimension : 3
shape : (2, 2, 2)
size : 8


### Methods in Numpy
zeros , ones , eye , identity , empty , full

##### Zeros

In [37]:
# zeros
arr = np.zeros(5)
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)

[0. 0. 0. 0. 0.]
dimension : 1
shape : (5,)
size : 5


In [39]:
arr = np.zeros((2,2))
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)

[[0. 0.]
 [0. 0.]]
dimension : 2
shape : (2, 2)
size : 4


In [40]:
arr = np.zeros((2,2,2))
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
dimension : 3
shape : (2, 2, 2)
size : 8


##### empty

In [42]:
arr = np.empty((2,2))
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)
print("data type :",arr.dtype)

[[0. 0.]
 [0. 0.]]
dimension : 2
shape : (2, 2)
size : 4
data type : float64


#### ones

In [43]:
arr = np.ones((2,2))
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)
print("data type :",arr.dtype)

[[1. 1.]
 [1. 1.]]
dimension : 2
shape : (2, 2)
size : 4
data type : float64


In [44]:
# changing data type
arr = np.ones((2,2),dtype=int)
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)
print("data type :",arr.dtype)

[[1 1]
 [1 1]]
dimension : 2
shape : (2, 2)
size : 4
data type : int32


##### eye

In [52]:
arr = np.eye(3)
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)
print("data type :",arr.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
dimension : 2
shape : (3, 3)
size : 9
data type : float64


In [49]:
arr = np.identity(3)
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)
print("data type :",arr.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
dimension : 2
shape : (3, 3)
size : 9
data type : float64


##### diag

In [56]:
arr = np.diag([2,3,4])
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)

[[2 0 0]
 [0 3 0]
 [0 0 4]]
dimension : 2
shape : (3, 3)


##### full 

In [69]:
arr = np.full((3,3),6) # all element same
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)

[[6 6 6]
 [6 6 6]
 [6 6 6]]
dimension : 2
shape : (3, 3)


##### arange

In [70]:
arr = np.arange(5,20)
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
dimension : 1
shape : (15,)


In [71]:
arr = np.arange(5,20,2) # (start,end,stepsize)
print(arr)
print("dimension :",arr.ndim)
print("shape :",arr.shape)

[ 5  7  9 11 13 15 17 19]
dimension : 1
shape : (8,)


##### Random --> Used to generate random number

1) np.random.randn() ----> generate random numbers from standard normal distribution (-3,+3)
2) np.random.rand() --> generates random numbers from uniform normal distribution (0,1)
3) np.random.randint() --> used to generate integers  

In [20]:
import numpy as np
arr = np.random.randn(10)
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (10,)
dimension : 1


array([ 1.33306367, -1.27439013, -2.90330568,  0.05932319, -1.69733146,
       -0.16536283,  1.3634639 ,  1.25489969, -0.26041704, -0.1898813 ])

In [23]:
arr = np.random.randn(3,3) # 2d
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (3, 3)
dimension : 2


array([[-0.76466698, -0.45584689,  0.34244893],
       [-1.10073374,  0.93291131, -0.05832857],
       [-0.26591829, -0.29421209,  0.01697826]])

In [24]:
arr = np.random.randn(1,3,3) # 3d
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (1, 3, 3)
dimension : 3


array([[[ 1.08200179, -0.62373424,  0.51802658],
        [ 0.66335759,  0.45875561, -0.98790501],
        [-0.50199884, -0.58147256, -1.88838213]]])

In [55]:
# random.rand() 
arr = np.random.rand(10) # 1d
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (10,)
dimension : 1


array([0.89808115, 0.40882275, 0.4272389 , 0.14237552, 0.89926896,
       0.35089578, 0.26742889, 0.48128393, 0.45709292, 0.03755655])

In [58]:
arr = np.random.rand(3,3) # 2d
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (3, 3)
dimension : 2


array([[0.34843627, 0.38150583, 0.26716556],
       [0.18276551, 0.47191423, 0.60682167],
       [0.92961886, 0.62480216, 0.59095513]])

In [59]:
arr = np.random.rand(2,3,3) # 3d
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (2, 3, 3)
dimension : 3


array([[[0.55789488, 0.95715565, 0.26455411],
        [0.95965698, 0.61470719, 0.54819473],
        [0.16755156, 0.32740468, 0.04877437]],

       [[0.89242857, 0.7808037 , 0.53833262],
        [0.71426634, 0.68379045, 0.80257346],
        [0.97652652, 0.82907423, 0.12604947]]])

In [72]:
# random.randint
arr = np.random.randint(10) 
# print("shape :",arr.shape)
# print("dimension :",arr.ndim)
arr

8

In [91]:
arr = np.random.randint(1,50,12) 
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (12,)
dimension : 1


array([15, 43, 24, 17, 30, 29, 47, 37, 44, 44, 47, 39])

In [94]:
arr = np.random.randint(0,50,(3,3)) 
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (3, 3)
dimension : 2


array([[45, 31,  8],
       [33, 15,  7],
       [15, 27,  5]])

In [103]:
arr = np.random.randint(1,50,(2,3,3)) 
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (2, 3, 3)
dimension : 3


array([[[43, 35, 22],
        [34,  8,  2],
        [33, 26, 17]],

       [[32, 15,  8],
        [10, 42, 41],
        [ 3, 25,  7]]])

In [120]:
# freezing random number 
np.random.seed(20)
arr = np.random.randint(1,50,(3,3)) 
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (3, 3)
dimension : 2


array([[36, 27, 16],
       [32, 29, 27],
       [10, 21, 12]])

### Reshaping of array

##### 1D to 2d and 3d

In [123]:
np.random.seed(20)
arr = np.random.randint(1,50,18) 
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (18,)
dimension : 1


array([36, 27, 16, 32, 29, 27, 10, 21, 12, 23,  8, 35, 33, 41, 22, 27, 27,
       20])

In [127]:
np.random.seed(20)
arr = np.random.randint(1,50,18).reshape(3,6) # 18 --> (1,18) , (2,9) , (3,6),(1,3,6)3d  , (2,3,3)
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (3, 6)
dimension : 2


array([[36, 27, 16, 32, 29, 27],
       [10, 21, 12, 23,  8, 35],
       [33, 41, 22, 27, 27, 20]])

In [129]:
np.random.seed(20)
arr = np.random.randint(1,50,18).reshape(2,3,3) # 18 --> (1,18) , (2,9) , (3,6),(1,3,6)3d  , (2,3,3)
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (2, 3, 3)
dimension : 3


array([[[36, 27, 16],
        [32, 29, 27],
        [10, 21, 12]],

       [[23,  8, 35],
        [33, 41, 22],
        [27, 27, 20]]])

##### 2d to 3d and 1d

In [131]:
np.random.seed(20)
arr = np.random.randint(1,50,(4,4))
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (4, 4)
dimension : 2


array([[36, 27, 16, 32],
       [29, 27, 10, 21],
       [12, 23,  8, 35],
       [33, 41, 22, 27]])

In [132]:
arr.reshape(2,2,4) # 3d to 3d

array([[[36, 27, 16, 32],
        [29, 27, 10, 21]],

       [[12, 23,  8, 35],
        [33, 41, 22, 27]]])

In [133]:
arr.reshape(16)

array([36, 27, 16, 32, 29, 27, 10, 21, 12, 23,  8, 35, 33, 41, 22, 27])

In [135]:
# to flatten the array we have ravel()
np.random.seed(20)
arr = np.random.randint(1,50,(4,4))
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (4, 4)
dimension : 2


array([[36, 27, 16, 32],
       [29, 27, 10, 21],
       [12, 23,  8, 35],
       [33, 41, 22, 27]])

In [136]:
# flattening
arr.ravel()

array([36, 27, 16, 32, 29, 27, 10, 21, 12, 23,  8, 35, 33, 41, 22, 27])

In [138]:
# flattening
arr.ravel().reshape(2,2,4)

array([[[36, 27, 16, 32],
        [29, 27, 10, 21]],

       [[12, 23,  8, 35],
        [33, 41, 22, 27]]])

### Indexing and slicing end]

##### 1d

In [147]:
np.random.seed(20)
arr = np.random.randint(1,50,12)
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (12,)
dimension : 1


array([36, 27, 16, 32, 29, 27, 10, 21, 12, 23,  8, 35])

In [148]:
print("Indexing :",arr[3])
print("slicing :",arr[2:4])
print("slicing with steps :",arr[1:10:2])

Indexing : 32
slicing : [16 32]
slicing with steps : [27 32 27 21 23]


##### 2d

In [149]:
np.random.seed(20)
arr = np.random.randint(1,50,(4,4))
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (4, 4)
dimension : 2


array([[36, 27, 16, 32],
       [29, 27, 10, 21],
       [12, 23,  8, 35],
       [33, 41, 22, 27]])

In [157]:
# syntax ---> array[row_start:row_end, col_start:col_end].

# extract 23
print("Indexing :",arr[2][1]) # double bracket notation
print("Indexing :",arr[2,1]) # single bracket notation

Indexing : 23
Indexing : 23


In [161]:
# extract [[27,10],
        # [23,8]]
print("slicing :\n",arr[:,:])

slicing :
 [[36 27 16 32]
 [29 27 10 21]
 [12 23  8 35]
 [33 41 22 27]]


In [163]:
# extract [[27,10],
        # [23,8]]
print("slicing :\n",arr[1:3,:])

slicing :
 [[29 27 10 21]
 [12 23  8 35]]


In [165]:
# extract [[27,10],
        # [23,8]]
print("slicing :\n",arr[1:3,1:3])

slicing :
 [[27 10]
 [23  8]]


In [168]:
# extract first column
print("slicing :\n",arr[:,1:2])

slicing :
 [[27]
 [27]
 [23]
 [41]]


##### 3d

In [177]:
np.random.seed(20)
arr = np.random.randint(1,50,(3,4,4))
print("shape :",arr.shape)
print("dimension :",arr.ndim)
arr

shape : (3, 4, 4)
dimension : 3


array([[[36, 27, 16, 32],
        [29, 27, 10, 21],
        [12, 23,  8, 35],
        [33, 41, 22, 27]],

       [[27, 20, 17, 39],
        [39, 17, 42, 38],
        [ 8, 38, 35,  7],
        [27, 14, 12, 26]],

       [[ 4, 11, 12, 14],
        [20, 31, 47, 33],
        [11, 44,  7, 12],
        [19,  4, 14, 18]]])

In [180]:
# extract 38 from 1d positioned 2d array
# syntax --> array[dim3_start:dim3_end, dim2_start:dim2_end, dim1_start:dim1_end].


print("Indexing :\n",arr[1,2,1]) # single bracket notation

Indexing :
 38


In [184]:
# slicing
# extract [[[35,7]],
#         [[12,26]]]

print("slicing :\n",arr[1:2,:,:])

slicing :
 [[[27 20 17 39]
  [39 17 42 38]
  [ 8 38 35  7]
  [27 14 12 26]]]


In [185]:
# slicing
# extract [[[35,7]],
#         [[12,26]]]

print("slicing :\n",arr[1:2,2:,:])

slicing :
 [[[ 8 38 35  7]
  [27 14 12 26]]]


In [186]:
# slicing
# extract [[[35,7]],
#         [[12,26]]]

print("slicing :\n",arr[1:2,2:,2:])

slicing :
 [[[35  7]
  [12 26]]]


### Broadcasting

In [190]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [191]:
arr = np.arange(3) + 5
arr

array([5, 6, 7])

In [192]:
# eg2
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [194]:
arr = np.ones((3,3)) + np.arange(3)
arr

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [196]:
# eg.3
arr = np.arange(3).reshape(3,1)
arr

array([[0],
       [1],
       [2]])

In [197]:
arr = np.arange(3).reshape(3,1) + np.arange(3)
arr

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Insertion and deletion in arrays

##### 1d array

In [11]:
import numpy as np
arr = np.arange(10,19)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [12]:
# insertion in 1d array
np.insert(arr,1,33) # insert single values

array([10, 33, 11, 12, 13, 14, 15, 16, 17, 18])

In [13]:
np.insert(arr,1,[33,44,55,66]) # insert multiple values

array([10, 33, 44, 55, 66, 11, 12, 13, 14, 15, 16, 17, 18])

In [16]:
np.delete(arr,1) # deleting single values

array([10, 12, 13, 14, 15, 16, 17, 18])

In [18]:
np.delete(arr,[2,3,4]) # deleting multiple values

array([10, 11, 15, 16, 17, 18])

##### 2d array

In [20]:
np.random.seed(3)
arr = np.random.randint(1,20,(3,3))
arr

array([[11,  4,  9],
       [ 1, 11, 12],
       [10, 11,  7]])

In [30]:
# 2d
# axis = 0 --> row
# axis = 1 --> column

np.insert(arr,1,33,axis=0) # inserting rowwise

array([[11,  4,  9],
       [33, 33, 33],
       [ 1, 11, 12],
       [10, 11,  7]])

In [45]:
np.insert(arr,3,[33,44,55],axis=0) # inserting different values rowwise

array([[11,  4,  9],
       [ 1, 11, 12],
       [10, 11,  7],
       [33, 44, 55]])

In [46]:
np.append(arr,[[22,33,44]],axis=0) # appending in last row

array([[11,  4,  9],
       [ 1, 11, 12],
       [10, 11,  7],
       [22, 33, 44]])

In [48]:
np.insert(arr,3,[55,66,77],axis=1) # inserting different values column wise

array([[11,  4,  9, 55],
       [ 1, 11, 12, 66],
       [10, 11,  7, 77]])

In [50]:
np.append(arr,[[22],[33],[44]],axis=1)

array([[11,  4,  9, 22],
       [ 1, 11, 12, 33],
       [10, 11,  7, 44]])

In [52]:
np.delete(arr,1,axis=1)

array([[11,  9],
       [ 1, 12],
       [10,  7]])

##### 3d

In [53]:
np.random.seed(3)
arr = np.random.randint(1,20,(1,3,3))
arr

array([[[11,  4,  9],
        [ 1, 11, 12],
        [10, 11,  7]]])

In [57]:
# in 3d array --> row--> axis=1 and column--> axis=2
np.insert(arr,1,[3,4,5],axis=1) 

array([[[11,  4,  9],
        [ 3,  4,  5],
        [ 1, 11, 12],
        [10, 11,  7]]])

In [58]:
np.insert(arr,1,[3,4,5],axis=2) 

array([[[11,  3,  4,  9],
        [ 1,  4, 11, 12],
        [10,  5, 11,  7]]])

In [59]:
np.delete(arr,1,axis=1)

array([[[11,  4,  9],
        [10, 11,  7]]])

### math operations

In [60]:
import numpy as np
arr = np.arange(10,19)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [62]:
arr * 2 # similar for / , + , - , // , %

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

In [63]:
# 2d
np.random.seed(3)
arr = np.random.randint(1,20,(3,3))
arr

array([[11,  4,  9],
       [ 1, 11, 12],
       [10, 11,  7]])

In [67]:
arr ** 2 # similar for / , + , - , // , % , **
# similary for 3d

array([[121,  16,  81],
       [  1, 121, 144],
       [100, 121,  49]])

In [68]:
# multiply , divide , power()

##### Dot product
The dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors), and returns a single number.

In [69]:
arr1 = np.array([[3,5],[9,4]]) 
arr2 = np.array([[11,1],[23,12]]) 

In [70]:
arr1

array([[3, 5],
       [9, 4]])

In [71]:
arr2

array([[11,  1],
       [23, 12]])

In [75]:
np.dot(arr1,arr2)

array([[148,  63],
       [191,  57]])

In [79]:
# eg. Multiply a 5x3 matrix by a 3x2 matrix.
arr1 = np.arange(1,16).reshape(5,3)
arr2 = np.arange(1,7).reshape(3,2)

In [80]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [81]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [83]:
np.dot(arr1,arr2)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### import mathematical mathods

In [86]:
arr = np.array([10,20,30,40,50,7])
arr

array([10, 20, 30, 40, 50,  7])

In [87]:
print("min :",np.min(arr)) # returns minimun number
print("Max :",np.max(arr)) # returns max number
print("sqrt :",np.sqrt(arr)) # returns sqrt
print("sin value :",np.sin(arr))  # sin value of every number
print("cos value :",np.cos(arr)) # cos value of every number
print("index of min number :",np.argmin(arr))
print("index of max number :",np.argmax(arr))
print("mean :",np.mean(arr))
print("std deviation :",np.std(arr))

min : 7
Max : 50
sqrt : [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 2.64575131]
sin value : [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485  0.6569866 ]
cos value : [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603  0.75390225]
index of min number : 5
index of max number : 4
mean : 26.166666666666668
std deviation : 15.496415356103775


##### normalization

In [94]:
np.random.seed(3)
arr1 = np.random.rand(4,4)
arr1

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761],
       [0.89294695, 0.89629309, 0.12558531, 0.20724288],
       [0.0514672 , 0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 , 0.59086282]])

In [95]:
arr1.mean()

0.45978011456689794

In [96]:
arr1.std()

0.2668577523181486

In [98]:
# to normalize we are using formula 

norm = (arr1-arr1.mean())/arr1.std()

In [99]:
norm.mean()

-1.942890293094024e-16

In [100]:
norm.std()

1.0

### joining and splitting

#### joining

In [104]:
# concatenate , syntax --> np.concatenate((array1, array2, ...), axis=0)
# vstack
# hstack
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [105]:
arr1

array([[1, 2],
       [3, 4]])

In [106]:
arr2

array([[5, 6],
       [7, 8]])

In [108]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [112]:
np.vstack((arr1,arr2)) # using vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [113]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [114]:
np.hstack((arr1,arr2)) # using vstack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##### splitting

In [132]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [133]:
np.split(arr,3) # splitting into 3qual parts

[array([1, 2]), array([3, 4]), array([5, 6])]

In [134]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [135]:
# Split into 2 parts along axis 0
np.split(arr2,2,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [136]:
# Split into 2 parts along axis 1
np.split(arr2,2,axis=1)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [137]:
# Split at specific indices
result = np.split(arr2, [1, 3], axis=1)
print(result)

[array([[1],
       [5]]), array([[2, 3],
       [6, 7]]), array([[4],
       [8]])]


In [139]:
# Split at specific indices
result = np.split(arr2, [0, 1], axis=0)
print(result)

[array([], shape=(0, 4), dtype=int32), array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [140]:
np.random.seed(3)
arr = np.random.randint(1,20,(4,4))
arr

array([[11,  4,  9,  1],
       [11, 12, 10, 11],
       [ 7,  1, 13,  8],
       [15, 18,  3,  3]])

In [147]:
np.split(arr,[1],axis=0)

[array([[11,  4,  9,  1]]),
 array([[11, 12, 10, 11],
        [ 7,  1, 13,  8],
        [15, 18,  3,  3]])]

### Searching and Sorting in array
1) np.where()
2) boolean indexing
3) argmin , argmax
4) find the element based on multiple
5) np.searchsorted()

In [16]:
# 1d array
import numpy as np
arr = np.array([10,20,20,30,40,50,60,5])
print("dimension :",arr.ndim)
print("shape :",arr.shape)

dimension : 1
shape : (8,)


In [17]:
np.where(arr==20) # np.where tells the index position of any element

(array([1, 2], dtype=int64),)

In [18]:
# boolean indexing
arr[arr>30]

array([40, 50, 60])

In [21]:
# argmin and argmax
print("index of min value :",np.argmin(arr))
print("index of max value :",np.argmax(arr))

index of min value : 7
index of max value : 6


In [22]:
# finding element based on multiple condition
arr[(arr>30) & (arr<50)]

array([40])

In [26]:
# np.searchsorted
arr = np.array([2,1,4,7,8,9])
arr

array([2, 1, 4, 7, 8, 9])

In [27]:
np.searchsorted(arr,3)

2

In [29]:
np.searchsorted(arr,8.8)

5

In [31]:
arr # changes wont reflect in original array

array([2, 1, 4, 7, 8, 9])

In [34]:
# 2d
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
np.where(arr==20)

(array([], dtype=int64), array([], dtype=int64))

In [36]:
np.where(arr==11)

(array([2], dtype=int64), array([2], dtype=int64))

In [37]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16])

In [38]:
arr[(arr>6) & (arr<15)]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
np.random.seed(5)
arr = np.random.randint(1,16,(4,4))
arr

array([[ 4, 15, 14,  7],
       [ 7,  1, 10,  9],
       [ 5,  8, 15, 12],
       [ 1, 15,  1,  8]])

In [41]:
np.where(arr==7)

(array([0, 1], dtype=int64), array([3, 0], dtype=int64))

### sorting

In [47]:
arr = np.array([2,1,4,7,8,9])
arr

array([2, 1, 4, 7, 8, 9])

In [48]:
np.sort(arr)

array([1, 2, 4, 7, 8, 9])

In [56]:
-np.sort(-arr)

array([9, 8, 7, 4, 2, 1])

In [57]:
np.sort(-arr)

array([-9, -8, -7, -4, -2, -1])

In [81]:
# 2d
np.random.seed(5)
arr = np.random.randint(1,16,(4,4))
arr

array([[ 4, 15, 14,  7],
       [ 7,  1, 10,  9],
       [ 5,  8, 15, 12],
       [ 1, 15,  1,  8]])

In [82]:
np.sort(arr,axis=0) # sorting rowwsie

array([[ 1,  1,  1,  7],
       [ 4,  8, 10,  8],
       [ 5, 15, 14,  9],
       [ 7, 15, 15, 12]])

In [73]:
np.sort(arr,axis=1) # sorting rowwsie

array([[ 4,  7, 14, 15],
       [ 1,  7,  9, 10],
       [ 5,  8, 12, 15],
       [ 1,  1,  8, 15]])

In [78]:
# 2d
np.random.seed(5)
arr = np.random.randint(0,16,(1,4,4))
arr

array([[[ 3, 14, 15, 13],
        [ 6,  6,  0,  9],
        [ 8,  4,  7, 14],
        [11,  0, 14,  0]]])

In [79]:
np.sort(arr,axis=1) # sorting rowwsie , axis=1 --> row in 3d array

array([[[ 3,  0,  0,  0],
        [ 6,  4,  7,  9],
        [ 8,  6, 14, 13],
        [11, 14, 15, 14]]])

In [80]:
np.sort(arr,axis=2) # sorting ro , axis=1 --> row in 3d array

array([[[ 3, 13, 14, 15],
        [ 0,  6,  6,  9],
        [ 4,  7,  8, 14],
        [ 0,  0, 11, 14]]])