In [1]:
pwd

'C:\\Users\\Acer\\OneDrive\\Desktop\\M.TECH DATA SCIENCE\\PYTHON\\udemy lectures'

In [2]:
2+2

4

In [3]:
2/4

0.5

In [4]:
2//4

0

In [5]:
123%10

3

In [6]:
a=5
a

5

In [7]:
a=10
a

10

In [8]:
a=a+a

In [9]:
a

20

In [10]:
type(a)

int

In [11]:
a=30.1
type(a)

float

In [12]:
x=100
y=0.1
m=x*y

In [13]:
m

10.0

In [14]:
print('hello world')

hello world


In [17]:
print('hello \nworld')
len('hello')

hello 
world


5

In [20]:
s='himanshu'
s[1:]

'imanshu'

In [21]:
s[::-1]

'uhsnamih'

In [22]:
s[0:5:2]

'hmn'

In [23]:
m='tinker'
m[1:4]

'ink'

In [24]:
name = 'himanshu'
name+'s'

'himanshus'

In [30]:
's'+name

'shimanshu'

In [31]:
name.upper()

'HIMANSHU'

In [32]:
name.lower()

'himanshu'

In [33]:
name.split()

['himanshu']

In [37]:
name.split("i")

['h', 'manshu']

In [41]:
print('The {} {} {}'.format('himanshu','singh','suryavanshi'))

The himanshu singh suryavanshi


In [42]:
print('The {2} {1} {0}'.format('himanshu','singh','suryavanshi'))

The suryavanshi singh himanshu


In [43]:
name='himanshu'
print('the name is {s}'.format(s=name))

the name is himanshu


In [46]:
print('the name is {}'.format(name))

the name is himanshu


In [47]:
print(f'the name is {name}')

the name is himanshu


In [48]:
age=25

In [49]:
print(f'the {name} is {age} years old')

the himanshu is 25 years old


In [50]:
l=[1,2,3]

In [51]:
len(l)

3

In [52]:
l[0]

1

In [53]:
l1=[4,5,6]
l2=l1+l

In [54]:
l2

[4, 5, 6, 1, 2, 3]

In [55]:
l2.append(7)

In [56]:
l2

[4, 5, 6, 1, 2, 3, 7]

In [57]:
l2[2]=8

In [58]:
l2

[4, 5, 8, 1, 2, 3, 7]

In [59]:
l2.pop()

7

In [60]:
l2

[4, 5, 8, 1, 2, 3]

In [61]:
l2.pop()
l2

[4, 5, 8, 1, 2]

In [63]:
l2.sort()

In [64]:
l2

[1, 2, 4, 5, 8]

In [65]:
l2.reverse()
l2

[8, 5, 4, 2, 1]

In [66]:
d={'k1':5,'k2':6,'k3':7}
d

{'k1': 5, 'k2': 6, 'k3': 7}

In [67]:
d['k2']

6

In [68]:
d = {'k1':123,'k2':[0,1,2],'k3':{'inside':100}}#using nested objects inside a dictionaries
d['k3']['inside']

100

In [69]:
d['k2'][2]

2

In [70]:
d['k4']=100

In [71]:
d

{'k1': 123, 'k2': [0, 1, 2], 'k3': {'inside': 100}, 'k4': 100}

In [72]:
t=(1,2,3)

In [73]:
t[1]

2

In [75]:
t=('a','a','a','b')

In [77]:
t.count('a')

3

In [78]:
t.count('b')

1

In [80]:
set(t)

{'a', 'b'}

In [81]:
text = 'hahahahhahahahahahahahahahahahahahahaha'
filename='jksh.txt'

In [82]:
file=open(filename,'w')
print(type(file))

<class '_io.TextIOWrapper'>


In [83]:
file.writelines(text)
file.close()
print('writing done')

writing done


In [85]:
file=open('jksh.txt','r')
file.read()

'hahahahhahahahahahahahahahahahahahahaha'

In [89]:
filename=open("C:\\Users\\Acer\\OneDrive\\Desktop\\M.TECH DATA SCIENCE\\PYTHON\\HIMANI'S CONTENT\\loopassignmentsandsolutionofifelse\\Ass1-solution.txt")

In [96]:
def add_num(num1,num2):
    return num1+num2
result=add_num(10,20)
result

30

In [97]:
def is_greater(x,y):
    if x>y:
        return True
    else:
        return False
is_greater(3,6)

False

In [100]:
def square(num):
    return num**2
my_nums=[1,2,3,4,5]

In [103]:
for item in map(square,my_nums):
print(item)

IndentationError: expected an indented block (504519633.py, line 2)

In [107]:
name='This is a global string'
def great():
    #Enclosing
    name = 'sammy'
    def hello():
        #local
        name = ' I an a local '
        print(' hello' +name)
    hello()
great()

 hello I an a local 


In [112]:
x=50
def fun(x):
    print(f' x is {x}')
fun(x)

 x is 50


In [6]:
# functions in numpy 
import numpy as np
arr = np.zeros(5)
print(arr)
print(arr.itemsize)
print(arr.nbytes)
print(arr.ndim)
print(arr.shape)

[0. 0. 0. 0. 0.]
8
40
1
(5,)


In [11]:
arr = np.zeros((5))
print(arr)
print(arr.itemsize)
print(arr.nbytes)
print(arr.ndim)
print(arr.shape)

[0. 0. 0. 0. 0.]
8
40
1
(5,)


In [12]:
arr = np.zeros(((5)))
print(arr)
print(arr.itemsize)
print(arr.nbytes)
print(arr.ndim)
print(arr.shape)

[0. 0. 0. 0. 0.]
8
40
1
(5,)


In [13]:
arr = np.zeros((5,3))
print(arr)
print(arr.itemsize)
print(arr.nbytes)
print(arr.ndim)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
8
120
2
(5, 3)


In [14]:
arr = np.zeros((2,4))
print(arr)
print(arr.itemsize)
print(arr.nbytes)
print(arr.ndim)
print(arr.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
8
64
2
(2, 4)


In [18]:
arr = np.ones(2)
arr.ndim

1

In [21]:
arr1=np.ones((2,2))

In [22]:
arr1.ndim

2