### Question 1
Create a 1D NumPy array containing the numbers 1 to 10.

In [1]:
import numpy as np
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### Question 2
Create a 2D array with shape (3, 4) filled with zeros.

In [2]:
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Question 3
Create a 3x3 identity matrix.

In [3]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Question 4
Create a 1D array of 10 random numbers and find the maximum and minimum values.

In [4]:
arr = np.random.rand(10)
max_val = arr.max()
min_val = arr.min()
print(f"Array: {arr}\nMax: {max_val}\nMin: {min_val}")

Array: [0.81262491 0.76184555 0.11040452 0.15574757 0.34940301 0.74131633
 0.0909659  0.16056593 0.69041407 0.31143749]
Max: 0.8126249091515062
Min: 0.09096590214072098


### Question 5
Create a 2D array and find the sum of all elements along the rows and columns.

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_sum = arr.sum(axis=1)
col_sum = arr.sum(axis=0)
print(f"Row sums: {row_sum}\nColumn sums: {col_sum}")

Row sums: [ 6 15 24]
Column sums: [12 15 18]


### Question 6
Generate a 5x5 array of random integers between 10 and 50.

In [6]:
arr = np.random.randint(10, 50, size=(5, 5))
print(arr)

[[28 31 25 19 36]
 [21 12 18 21 13]
 [27 32 49 15 23]
 [26 41 13 41 20]
 [28 15 41 42 43]]


### Question 7
Create a random array of shape (3, 4) and normalize it (i.e., scale the values so that the mean is 0 and the standard deviation is 1).

In [7]:
arr = np.random.rand(3, 4)
normalized_arr = (arr - arr.mean()) / arr.std()
print(normalized_arr)

[[ 0.37007345 -1.23817261 -1.79126379  1.1704956 ]
 [-0.38162471  0.54903765  1.34788111  0.68879366]
 [-1.36627996  0.78960338  0.43728352 -0.5758273 ]]


### Question 8
Create a 1D array of 12 elements and reshape it into a 3x4 matrix.

In [8]:
arr = np.arange(12)
reshaped_arr = arr.reshape((3, 4))
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Question 9
Flatten a 2D array into a 1D array.

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_arr = arr.flatten()
print(flattened_arr)

[1 2 3 4 5 6 7 8 9]


### Question 10
Create a 3x3 matrix and print the element at row 2, column 3.

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2])

6


### Question 11
Create a 3D array of shape (2, 3, 4) and access the element at position (1, 2, 3).

In [11]:
arr = np.arange(24).reshape((2, 3, 4))
print(arr[1, 2, 3])

23


### Question 12
Slice the 2D array to get the first two rows and the last two columns.

In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sliced_arr = arr[:2, -2:]
print(sliced_arr)

[[3 4]
 [7 8]]


### Question 13
Create two arrays, one with shape (3, 1) and the other with shape (1, 4). Use broadcasting to add them.

In [13]:
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[10, 20, 30, 40]])
result = arr1 + arr2
print(result)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


### Question 14
Multiply a 2D array by a 1D array using broadcasting.

In [14]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([1, 0, -1])
result = arr1 * arr2
print(result)

[[ 1  0 -3]
 [ 4  0 -6]
 [ 7  0 -9]]


### Question 15
Create a 4x4 array of random numbers and replace all values greater than 0.5 with 1.

In [15]:
arr = np.random.rand(4, 4)
arr[arr > 0.5] = 1
print(arr)

[[1.         1.         0.32348463 1.        ]
 [0.06412609 1.         0.38893295 1.        ]
 [1.         0.26121951 0.36878591 0.33252172]
 [0.31092945 1.         0.15452745 1.        ]]


### Question 16
Create a 5x5 identity matrix and add a 5x5 matrix of ones to it.

In [16]:
identity_matrix = np.eye(5)
ones_matrix = np.ones((5, 5))
result = identity_matrix + ones_matrix
print(result)

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


### Question 17
Create a 3D array of shape (2, 3, 4) and reverse the order of elements along the third axis.

In [17]:
arr = np.arange(24).reshape((2, 3, 4))
reversed_arr = arr[:, :, ::-1]
print(reversed_arr)

[[[ 3  2  1  0]
  [ 7  6  5  4]
  [11 10  9  8]]

 [[15 14 13 12]
  [19 18 17 16]
  [23 22 21 20]]]


### Question 18
Create a 2D array of shape (4, 5) and calculate the mean of each row.

In [18]:
arr = np.random.rand(4, 5)
row_means = arr.mean(axis=1)
print(row_means)

[0.34827399 0.49503731 0.47485443 0.59179378]


### Question 19
Create an array of 20 random integers between 1 and 100. Sort the array and find the median value.

In [19]:
arr = np.random.randint(1, 101, 20)
sorted_arr = np.sort(arr)
median_val = np.median(sorted_arr)
print(f"Sorted Array: {sorted_arr}\nMedian: {median_val}")

Sorted Array: [ 1  1  4 11 12 17 22 30 31 42 62 65 72 72 73 79 83 84 85 99]
Median: 52.0


### Question 20
Create two 1D arrays and use broadcasting to compute the outer product.

In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
outer_product = np.outer(arr1, arr2)
print(outer_product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
