# Daily Tasks


### 1. Popular Python Modules, Libraries, & Frameworks for Different Domains


- **Web Development:**


  - **Django:** High-level web framework for building web applications.


  - **Flask:** Lightweight web framework for creating web applications.


  - **FastAPI:** Modern, fast web framework for building APIs with Python 3.7+.


- **Data Science & Machine Learning:**


  - **NumPy:** Fundamental package for numerical computations.


  - **Pandas:** Data manipulation and analysis library.


  - **Matplotlib:** Plotting library for creating static, animated, and interactive visualizations.


  - **SciPy:** Library for scientific and technical computing.


  - **scikit-learn:** Machine learning library for data analysis and modeling.


  - **TensorFlow:** Open-source machine learning framework for numerical computation.


  - **PyTorch:** Deep learning framework for building neural networks.


- **Web Scraping:**


  - **Beautiful Soup:** Library for parsing HTML and XML documents.


  - **Scrapy:** Framework for web scraping and crawling.


- **Automation:**


  - **Selenium:** Library for automating web browsers.


  - **PyAutoGUI:** Cross-platform GUI automation Python module.


- **Networking:**


  - **Requests:** Simple HTTP library for making network requests.


  - **Paramiko:** Library for SSH2 protocol to connect to remote machines.


- **Game Development:**


  - **Pygame:** Set of Python modules for writing video games.


- **Natural Language Processing:**


  - **NLTK:** Natural Language Toolkit for working with human language data.


  - **spaCy:** Library for advanced NLP with Python.


  - **Gensim:** Topic modeling and document similarity library.


- **Computer Vision:**


  - **OpenCV:** Library for real-time computer vision.


### 2. Research on Statistical Measures


- **Min:** The smallest value in a dataset.


- **Max:** The largest value in a dataset.


- **Mean:** The average of all values in a dataset.


- **Median:** The middle value in a dataset when it is ordered.


- **Mode:** The most frequently occurring value(s) in a dataset.


- **Deviation (Standard Deviation):** A measure of the amount of variation or dispersion in a dataset.


- **Variance:** The average of the squared differences from the mean, indicating the spread of a dataset.


- **Correlation:** A statistical measure that expresses the extent to which two variables are linearly related.


### 3. Use Cases of NumPy, Pandas, & Matplotlib


- **NumPy:**


  - Efficiently handle large datasets.


  - Perform mathematical operations on arrays and matrices.


  - Support for linear algebra, Fourier transform, and random number capabilities.


- **Pandas:**


  - Data cleaning and preparation.


  - Data analysis and manipulation with DataFrame and Series.


  - Handling time series data.


- **Matplotlib:**


  - Creating static, interactive, and animated plots.


  - Visualizing data distributions, trends, and relationships.


  - Customizing plots with labels, colors, and annotations.


# Practice Questions


1. **Create a 4x4 zero array:**


In [30]:
import numpy as np


In [31]:
zero_array = np.zeros((4, 4))


In [32]:
zero_array


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

```


2. **Create a 2x3 ones array:**


In [33]:
ones_array = np.ones((2, 3))


In [34]:
ones_array


array([[1., 1., 1.],
       [1., 1., 1.]])

```


3. **Create a 3x3 full array filled with the value 2:**


In [35]:
full_array = np.full((3, 3), 2)


In [36]:
full_array


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

```


4. **Create a 4x4 identity matrix:**


In [37]:
identity_matrix = np.eye(4)


In [38]:
identity_matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

```


5. **Create a linear series from 0 to 20 with a step of 4:**


In [39]:
linear_series = np.arange(0, 21, 4)


In [40]:
linear_series


array([ 0,  4,  8, 12, 16, 20])

```


# Interview Questions


1. **What is the difference between `np.zeros()` and `np.ones()`?**


  - `np.zeros()` creates an array filled with zeros, while `np.ones()` creates an array filled with ones.


2. **How do you create a 3x3 identity matrix using NumPy?**


In [41]:
identity_matrix = np.eye(3)


In [42]:
identity_matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

```


3. **What is the purpose of the `np.full()` function?**


  - `np.full()` creates an array of a specified shape and fills it with a specified value.


4. **How do you create a linear series with a specified start, stop, and step values?**


In [43]:
linear_series = np.arange(1,50,2)

In [44]:
linear_series


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

```


5. **What is the difference between a zero array and a full array?**


  - A zero array is filled with zeros, while a full array is filled with a specified value.


6. **Can you create a NumPy array with random values from a normal distribution?**


In [45]:
random_normal_array = np.random.normal(loc=0.0, scale=1.0, size=(3, 3))


In [46]:
random_normal_array


array([[ 1.27364278, -0.4435695 , -0.36206417],
       [-0.83243491,  0.1569086 ,  0.37702052],
       [-0.9448307 ,  0.57420011, -0.34993543]])

```


7. **How do you create a 2x2 ones array using NumPy?**


In [47]:
ones_array = np.ones((2, 2))


In [48]:
ones_array


array([[1., 1.],
       [1., 1.]])

```


8. **What is the purpose of the `np.eye()` function?**


  - `np.eye()` creates an identity matrix with ones on the diagonal and zeros elsewhere.


9. **Can you create a NumPy array with a specified shape and fill value?**


In [49]:
full_array = np.full((4,4), 5)


In [50]:
full_array


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

```


10. **How do you create a distribution array with random values from a uniform distribution?**


In [51]:
random_uniform_array = np.random.uniform(low=0.0, high=1.0, size=(3, 3))


In [52]:
random_uniform_array


array([[0.38944268, 0.34763722, 0.4284262 ],
       [0.64673591, 0.30016568, 0.97340024],
       [0.61788196, 0.01866363, 0.25677849]])

```
