In [15]:
# array searching 
# where , boolean indexing , argmin or armax , using multiple condition , np.searchsorted

In [16]:
import numpy as np
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [17]:
np.where(arr==20)

(array([1], dtype=int64),)

In [20]:
# bolean indexing
arr[arr>20]

array([30, 40, 50])

In [21]:
np.argmax(arr)

4

In [22]:
np.argmin(arr)

0

In [23]:
arr[(arr>20) & (arr<50)]

array([30, 40])

In [24]:
arr = [10,1,2,8,3,5,7,9]

In [25]:
arr

[10, 1, 2, 8, 3, 5, 7, 9]

In [27]:
np.searchsorted(arr,6)

6

In [30]:
arr = np.array([26,2,5,3,65,11,2,4,9])
arr

array([26,  2,  5,  3, 65, 11,  2,  4,  9])

In [31]:
np.sort(arr)

array([ 2,  2,  3,  4,  5,  9, 11, 26, 65])

In [32]:
-np.sort(-arr)

array([65, 26, 11,  9,  5,  4,  3,  2,  2])

In [41]:
np.random.seed()
arr = np.random.randint(1,30,12).reshape(4,3)
arr

array([[ 8,  1, 14],
       [ 4, 12, 12],
       [18, 26,  6],
       [ 4, 20, 12]])

In [42]:
np.sort(arr,axis=0)

array([[ 4,  1,  6],
       [ 4, 12, 12],
       [ 8, 20, 12],
       [18, 26, 14]])

In [43]:
np.sort(arr,axis=1)

array([[ 1,  8, 14],
       [ 4, 12, 12],
       [ 6, 18, 26],
       [ 4, 12, 20]])

In [44]:
ar = np.array(['Bhopal', 'Indore', 'Ahmadabad', "Delhi"])
ar

array(['Bhopal', 'Indore', 'Ahmadabad', 'Delhi'], dtype='<U9')

In [45]:
arr.sort()