# Numpy Practice Questions with Answers

## Easy Level Questions

1. **Create a numpy array of integers from 0 to 9.**

In [2]:

import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


2. **Create a 3x3 numpy array filled with zeros.**

In [3]:

arr = np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. **Create a 3x3 numpy array filled with ones.**

In [4]:

arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4. **Create a 2x2 numpy array with random values.**

In [5]:

arr = np.random.rand(2, 2)
print(arr)


[[0.3699384  0.68682869]
 [0.01013821 0.47810448]]


5. **Create a 1D numpy array of 5 elements all equal to 7.**

In [6]:

arr = np.full(5, 7)
print(arr)


[7 7 7 7 7]


6. **Create a numpy array with values ranging from 10 to 50.**

In [7]:

arr = np.arange(10, 51)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


7. **Create a 4x4 identity matrix.**

In [8]:

arr = np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


8. **Reverse a numpy array of integers from 0 to 9.**

In [9]:

arr = np.arange(10)[::-1]
print(arr)


[9 8 7 6 5 4 3 2 1 0]


9. **Find the shape of a given numpy array.**

In [10]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)


(2, 3)


10. **Find the data type of elements in a numpy array.**

In [11]:

arr = np.array([1, 2, 3])
print(arr.dtype)


int32


11. **Convert a list of integers to a numpy array.**

In [12]:

lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
print(arr)


[1 2 3 4 5]


12. **Create a numpy array of 10 evenly spaced numbers between 1 and 10.**

In [13]:

arr = np.linspace(1, 10, 10)
print(arr)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


13. **Reshape a numpy array of shape (6,) to (2,3).**

In [14]:

arr = np.arange(6).reshape(2, 3)
print(arr)


[[0 1 2]
 [3 4 5]]


14. **Stack two numpy arrays vertically.**

In [15]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)


[[1 2 3]
 [4 5 6]]


15. **Stack two numpy arrays horizontally.**

In [16]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


## Medium Level Questions

16. **Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal.**

In [17]:

arr = np.diag([1, 2, 3, 4], k=-1)
print(arr)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


17. **Find the sum of all the elements in a numpy array.**

In [18]:

arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print(total)


15


18. **Find the mean of all the elements in a numpy array.**

In [19]:

arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
print(mean)


3.0


19. **Create a random array of 10 elements and replace the maximum value with 0.**

In [20]:

arr = np.random.rand(10)
arr[arr.argmax()] = 0
print(arr)


[0.18994182 0.50992071 0.57249452 0.13322521 0.60124426 0.31070615
 0.67976826 0.19202959 0.         0.39000977]


20. **Find the indices of non-zero elements in a numpy array.**

In [21]:

arr = np.array([0, 2, 0, 3, 4])
indices = np.nonzero(arr)
print(indices)


(array([1, 3, 4], dtype=int64),)


21. **Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).**

In [22]:

arr1 = np.random.rand(5, 3)
arr2 = np.random.rand(3, 2)
product = np.dot(arr1, arr2)
print(product)


[[0.60902311 0.77443432]
 [0.93418606 1.12228877]
 [0.96988524 1.08389687]
 [0.68286998 0.7207467 ]
 [0.81934681 0.61448929]]


22. **Subtract the mean of each row of a matrix.**

In [23]:

arr = np.random.rand(3, 3)
mean_subtracted = arr - arr.mean(axis=1, keepdims=True)
print(mean_subtracted)


[[-0.06304444 -0.23327637  0.2963208 ]
 [-0.13698495  0.01862931  0.11835565]
 [-0.0762319   0.28031196 -0.20408006]]


23. **Sort a numpy array of random values.**

In [24]:

arr = np.random.rand(10)
arr.sort()
print(arr)


[0.22733149 0.33894314 0.34635372 0.39250515 0.63207678 0.70322325
 0.74638254 0.74710329 0.92830959 0.99933459]


24. **Create a 3x3 matrix and compute the eigenvalues.**

In [25]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
eigenvalues = np.linalg.eigvals(arr)
print(eigenvalues)


[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


25. **Compute the inverse of a given square matrix.**

In [26]:

arr = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(arr)
print(inverse)


[[-2.   1. ]
 [ 1.5 -0.5]]


26. **Find the maximum and minimum values in a numpy array.**

In [27]:

arr = np.random.rand(10)
max_value = np.max(arr)
min_value = np.min(arr)
print(f"Max: {max_value}, Min: {min_value}")


Max: 0.8812467919317201, Min: 0.00017146306880455597


27. **Create a 3x3 matrix with random values and find the row and column index of the maximum value.**

In [28]:

arr = np.random.rand(3, 3)
index = np.unravel_index(np.argmax(arr), arr.shape)
print(index)


(0, 0)


28. **Create a 1D array and compute the cumulative sum.**

In [29]:

arr = np.array([1, 2, 3, 4, 5])
cumsum = np.cumsum(arr)
print(cumsum)


[ 1  3  6 10 15]


29. **Check if two numpy arrays are equal.**

In [30]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
equality = np.array_equal(arr1, arr2)
print(equality)


True


30. **Find the unique elements of a numpy array.**

In [31]:

arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(arr)
print(unique_elements)


[1 2 3 4 5]


## Hard Level Questions

31. **Create a random 10x10 matrix and find the position (index) of the maximum value.**

In [32]:

arr = np.random.rand(10, 10)
max_index = np.unravel_index(np.argmax(arr), arr.shape)
print(max_index)


(7, 1)


32. **Create a random vector of size 30 and find the mean value.**

In [33]:

arr = np.random.rand(30)
mean_value = np.mean(arr)
print(mean_value)


0.4781751102498299


33. **Generate a 10x10 matrix of random numbers and subtract the row mean from each element.**

In [34]:

arr = np.random.rand(10, 10)
row_mean_subtracted = arr - arr.mean(axis=1, keepdims=True)
print(row_mean_subtracted)


[[-0.1975578  -0.15284458 -0.25135011  0.03504952  0.25539919 -0.35643237
   0.3168812   0.20274416  0.39852519 -0.2504144 ]
 [ 0.41946624 -0.19015032 -0.252541    0.26014592  0.15391289  0.17820493
  -0.07296108 -0.1952531  -0.35613857  0.05531411]
 [ 0.08270684  0.31932992 -0.16900288  0.58263756 -0.35292581  0.42315928
   0.25345719 -0.41568825 -0.35153091 -0.37214296]
 [-0.13033904  0.26565419 -0.11526956  0.20425744 -0.51946407  0.32515878
   0.22731956 -0.31385561  0.23504566 -0.17850737]
 [-0.03067821 -0.34780224 -0.32191694 -0.41871883  0.41372206 -0.03084305
  -0.16016509  0.40949624  0.23076     0.25614607]
 [ 0.08098101 -0.51215872  0.22518913  0.23907043  0.0050226   0.09949182
   0.02174593  0.41539122 -0.12068558 -0.45404783]
 [ 0.05068159  0.47174035  0.36959704 -0.37364693 -0.29104534  0.07172525
  -0.28995601 -0.10078346  0.50972751 -0.41804   ]
 [-0.24068361  0.20000336  0.29218927 -0.06204417  0.0075249  -0.15459456
  -0.14773816 -0.06669266  0.13158825  0.04044738]


34. **Create two random matrices A and B, compute A * B (element-wise product) and A @ B (matrix product).**

In [35]:

A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
element_wise_product = A * B
print(element_wise_product)

matrix_product = A @ B
print(matrix_product)


[[0.38057113 0.55594531 0.02055365]
 [0.07511635 0.78791173 0.04726727]
 [0.11158453 0.02214984 0.61272572]]
[[0.73255205 1.14966805 0.58022295]
 [0.8278772  1.19532447 0.36524504]
 [0.65155628 0.52723819 0.68097505]]


35. **Solve the following system of linear equations: 3x + y = 9 and x + 2y = 8.**

In [36]:

a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
solution = np.linalg.solve(a, b)
print(solution)


[2. 3.]


36. **Compute the determinant of a given square matrix.**

In [37]:

arr = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(arr)
print(determinant)


-2.0000000000000004


37. **Create a 3D numpy array and compute the sum along one axis.**

In [38]:

arr = np.random.rand(3, 3, 3)
sum_along_axis = np.sum(arr, axis=0)
print(sum_along_axis)


[[1.39955742 2.2143529  1.29806126]
 [1.64511127 2.07272564 2.22636804]
 [1.60240932 1.82833829 0.7059628 ]]


38. **Create a random 4x4 matrix and normalize it (so that the sum of all elements is 1).**

In [39]:

arr = np.random.rand(4, 4)
normalized_arr = arr / arr.sum()
print(normalized_arr)


[[0.05129888 0.00161329 0.07239552 0.04969095]
 [0.09175099 0.04225954 0.03252775 0.0680538 ]
 [0.04693218 0.08963801 0.09435563 0.06062763]
 [0.09983941 0.03585572 0.08520195 0.07795875]]


39. **Generate a 2D Gaussian-like array.**

In [40]:

x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
gaussian = np.exp(-((d - mu)**2 / (2.0 * sigma**2)))
print(gaussian)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

40. **Create a 3D array of shape (3,3,3) with random values and compute the mean along each axis.**

In [41]:

arr = np.random.rand(3, 3, 3)
mean_along_axes = np.mean(arr, axis=(0, 1, 2))
print(mean_along_axes)


0.5033252959280902
